Update connection management doc
stinebuu/nest-simulator pull request #8
Opened 2020-12-07 22:35 UTC by jougs

Here's my major update and rewrite of the connection management documentation as promised in https://github.com/nest/nest-simulator/pull/1834. In particular, I tried to make the language and code snippets more consistent and more user centric, but I took the liberty to also rewrite major parts of the text. Sorry for this being so massive!

Looking at the changeset is probably not very helpful here (although I recommend doing it anyway, if only to admire the sheer volume) and I suggest to review by giving the rendered version a thorough read over a big pot of tea or coffee instead ;-)

Here are some general remarks (mainly for @sarakonradi, @steffengraber, @terhorstd):
* How shall we write NodeCollection and SynapseCollection? Always as <code>\`\`typewriter\`\`</code>, <code>\`italic\`</code>, plain? This is massively inconsistent all over the documentation.
* We also need to be more consistent on when to use `:math:` when referring to mathematical variables and when to just use italics.
* How to refer to dictionary entities like `keys` and `values`? I propose to use <code>\`\`typewriter\`\`</code> for keys and <code>\`italic\`</code> for values and other variables.
* The situation regarding the first three points is quite messy throughout the whole documentation and I really think we need a guideline document for this the sooner the better. Or is this already existing and I missed it?
* I think we urgently need an automatic linking of all PyNEST functions that are mentioned throughout the documentation (e.g. <code>\`\`nest.Connect()\`\`</code> to the corresponding anchor in the [PyNEST API documentation](https://nest-simulator.readthedocs.io/en/latest/ref_material/pynest_apis.html). The absence of this functionality leads to heaps of redundancy and repetitive descriptions of the same thing over and over again.
* I think the style (as in CSS) for the glossary items looks totally out of place. Just have a look at where `_lbl`, `_hpc`, and `_hom` are defined in the document.

And some more specific ones about this guide (for @stinebuu, @hakonsbm, @heplesser)
* Should we drop the description of `Get`/`SetStatus` for SynapseCollections? I think get() and set() or the dot-notation are much nicer anyway
* I'd like to rename `receptor_type` to just `receptor`. I think that's more accurately describing the matter and I am not aware of a possible name clash.
* I never really know if I have to write `all_to_all` or `all-to-all`. The same also applies to basically all rules. The documentation even adds to the confusion because it uses the first when referring to the rule and the second (or using spaces instead of dashed) when referring to the concept. I propose to solve the problem by accepting all variants (i.e. treat `-`, `_` and ` ` equally) in the `ConnBuilder` and just do *the right thing*™ regardless. IMO the chance for collisions here is negligible.
* I kind of dislike the term *distributed parameters* and would prefer something like *randomized parameters* or similar. As I could not come up with something I *loved*, I did not make a corresponding change. Maybe you have a good idea on this?

Yes, I know this PR in @stinebuu's repository is probably the wrong place for all this. I just wanted to get this off my mind and will happily create a separate issue for this if you think that'd be better.

2020-12-08 07:50 UTC, heplesser commented
Great work, @jougs (but have only parsed it quickly so far). I agree that a clear style guide (if not available yet) would be very useful, also for related projects. Auto-linking would also help tremendously. 

In a guide such as this we should stick to *the* recommended way of doing things, such as `get()` and `set()` for connections. Legacy functions we still support can be documented in the function documentation, so users who find `GetStatus()` in legacy code can find out what it means. But we should not encourage any further use.

I would argue for `all_to_all`, simply because it is a valid Python name, in case we ever want to turn rules also into Python objects (or `AllToAll` if we want to go for proper PEP8-compatible class names). The general rule: If it is Python, use only `_`, if it is English, use only "-".

I noticed, btw, that the headings of the individual rule sections in the guide are typeset lowercase with spaces, eg "fixed indegree". I think the headings should be typeset as English, because they describe concepts, thus "Fixed in-degree" (not 100% certain about the hyphen, but I assume "indegree" is not a word in the English language?).

"Randomised parameter" sounds reasonable to me (and another question for the style guide: US or British English?).

The motivation for the `receptor_type` was, I believe, the following: For certain types of receptors, especially second-messenger receptors such as GABA_B, you cannot lump synapses due to non-linear effects: 100 spikes to one synapse do not evoke the same PSC as one spike each through 100 synapses. In neuron models implementing this, each individual connection to a given target neuron with `receptor_type=='GABA_B'` needs to go to a separate receptor or rather a separate synapse instance, while the default in NEST is to have lumped synapses. Maybe we should discuss our terminology in general on this point (in a separate issue), since we also have the mix-up of synapse and synapse model in NEST.

2020-12-08 08:31 UTC, terhorstd commented
Wow, that's quite some work. Need more :coffee: ...

Some thoughts on your questions:
> * How shall we write NodeCollection and SynapseCollection? Always as `` ``typewriter`` ``, `` `italic` ``, plain? This is massively inconsistent all over the documentation.

Neither. NodeCollection and SynapseCollection are either used as *class names* or as *concepts*. In the former case they should be typeset as code, in the second case I would be fine having the text continue just plain without formatting. Typewriter and italic are styles, which we would apply to code or concept strings. It should however be an independent decision making concept strings italic or e.g. orange. Separation of style from semantics is imho an important aspect here.

> * We also need to be more consistent on when to use `:math:` when referring to mathematical variables and when to just use italics.

This is a good example. Marking something as `:math:` would defer the decision of font and style to the actual output. Marking variables as "italic" we would loose the distinction to e.g. concepts, if they are also marked in italic. If we decide to do concepts in blue, we do not want all variables to turn blue, too.

> * How to refer to dictionary entities like `keys` and `values`? I propose to use `` ``typewriter`` `` for keys and `` `italic` `` for values and other variables.

Ideally I'd say by marking as code: ` ``key`` ` and ` ``value`` ` (e.g.  ` ``42`` ` or ` ``"text"`` `)

> * The situation regarding the first three points is quite messy throughout the whole documentation and I really think we need a guideline document for this the sooner the better. Or is this already existing and I missed it?

I agree to both. @sarakonradi could best comment on this.

> * I think we urgently need an automatic linking of all PyNEST functions that are mentioned throughout the documentation (e.g. `` ``nest.Connect()`` `` to the corresponding anchor in the [PyNEST API documentation](https://nest-simulator.readthedocs.io/en/latest/ref_material/pynest_apis.html). The absence of this functionality leads to heaps of redundancy and repetitive descriptions of the same thing over and over again.

I fully agree. @sarakonradi and @sgraber know best about this.

> * I think the style (as in CSS) for the glossary items looks totally out of place. Just have a look at where `_lbl`, `_hpc`, and `_hom` are defined in the document.

A less obtrusive style could be used, yes.

> And some more specific ones about this guide (for @stinebuu, @hakonsbm, @heplesser)
>  * Should we drop the description of `Get`/`SetStatus` for SynapseCollections? I think get() and set() or the dot-notation are much nicer anyway

I am in favour of using proper object orientation. `Get`/`SetStatus` suggests users to think with a "global state" in mind, wrongly encouraging global variables and bad coding style/architecture.

> * I'd like to rename `receptor_type` to just `receptor`. I think that's more accurately describing the matter and I am not aware of a possible name clash.

Since the receptor_type is a mapping to names, I could imagine this is more a neuroscience question: would you connect to the "NMDA `receptor`" or to the "NMDA `receptor_type`"?

> * I never really know if I have to write `all_to_all` or `all-to-all`. The same also applies to basically all rules. The documentation even adds to the confusion because it uses the first when referring to the rule and the second (or using spaces instead of dashed) when referring to the concept. I propose to solve the problem by accepting all variants (i.e. treat `-`, `_` and ` ` equally) in the `ConnBuilder` and just do _the right thing_™ regardless. IMO the chance for collisions here is negligible.

Given the transition to `projections` being represented as classes, for me only the coding style consistent `AllToAll` comes to mind. I guess that's also what we will discuss, as you mentioned in yesterdays meeting.

> * I kind of dislike the term _distributed parameters_ and would prefer something like _randomized parameters_ or similar. As I could not come up with something I _loved_, I did not make a corresponding change. Maybe you have a good idea on this?

What about _variable parameters_? Would catch the randomness and the functions, at the same time, would it?

> Yes, I know this PR in @stinebuu's repository is probably the wrong place for all this. I just wanted to get this off my mind and will happily create a separate issue for this if you think that'd be better.

I think this is part of documentation documentation and @sarakonradi should collect it in the right place.

2020-12-08 11:56 UTC, sarakonradi commented
Thanks for the comprehensive work, @jougs! This is indeed a lot. :+1: 

> I think we urgently need an automatic linking of all PyNEST functions that are mentioned throughout the documentation (e.g. ``nest.Connect()`` to the corresponding anchor in the PyNEST API documentation. The absence of this functionality leads to heaps of redundancy and repetitive descriptions of the same thing over and over again.

I completely agree and am also in favor of the automatic linking of PyNEST functions. Perhaps @sgraber would like to add something.

> I agree that a clear style guide (if not available yet) would be very useful, also for related projects. 

We do not have a style guide yet, but it certainly would be beneficial and is on our to-do list. Alongside the suggestions from this conversation, the document could include the recommendations discussed at the Hackathons and Doc Work Meetings.

> I suggest to always treat _text_ as emphasis and use :math:/:code: etc. directives wherever possible, in order to keep this differentiation.

I agree with @terhorstd here and think we should mention this differentiation in the style guide. 

> A less obtrusive style could be used, yes.

Yes, that sounds good to me.

> I think this is part of documentation documentation and @sarakonradi should collect it in the right place.

My suggestion would be to address the points specific to the Connection Management Guide in #1834 and to create separate issues for the style guide and auto-linking (to prevent feature creep).

2020-12-18 14:00 UTC, stinebuu requested changes
Thanks for this! I have some suggestions on wording, have a look and see what you think.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +also just be a the name of the synapse model to be used, an object
```suggestion
also just be the name of the synapse model to be used, an object
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +dictionary, with the mandatory key `synapse_model` as well as optional
`synapse_model` is not mandatory. It is possible to just change the weight and delay. Then `static_synapse` is used as model.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
>      Connect(pre, post, conn_spec, syn_spec)
It is technically possible to call `Connect(pre, post, syn_spec=syn_spec)`, but I am not sure if we need to mention it?

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
>      Connect(pre, post, conn_spec, syn_spec)
Just noticed it is written further down! So you can ignore this comment. :)

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +arguments are mandatory.
I'm wondering if the sentence `These two first arguments are mandatory` is necessary, as we say that the simplest case needs a source and target.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
Should we have a sentence like `A description of all of NEST's connection rules is given below` or something similar? I think the transition from the general information of the rules and then the rules themselves is a little abrupt, but it might just be me.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
>  fixed indegree
Another problem with writing out the rules is that it looks a little strange to have only lower case letters in a header.. I don't necessarily know if we should fix this though.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +The nodes in ``pre`` are randomly connected with the nodes in ``B``
```suggestion
The nodes in ``A`` are randomly connected with the nodes in ``B``
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +The `i`th node in ``A`` is connected to the `i`th node in ``B``. The
This does not render properly for me on ReadTheDocs. Maybe you need a space between i and th?

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +                 'allow_autapses': False, 'make_symmetric': True}
```suggestion
    conn_spec_dict = {'rule': 'symmetric_pairwise_bernoulli', 'p': p,
                      'allow_autapses': False, 'make_symmetric': True}
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +(specified as a ``nest.Parameter``). One synapse dictionary can
I think I might have added the reference to `nest.Parameter`, but looking at it now I think it will confuse the reader more than adding something.

```suggestion
All parameters can be either scalars, arrays or distributions.
One synapse dictionary can
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +and connections will be using the model `stdp_synapse`. All synapses
Don't we usually refer to synapses as synapse model (and not just model)?

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +object.
```suggestion
object, and the connection rule ``one_to_one`` is used.
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +connected are only known internally, or have to be retrieved manually
```suggestion
connected are only known internally, and have to be retrieved manually
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +concept called `collocated synapses`. This allows to create several
```suggestion
concept called `collocated synapses`. This allows the creation of several
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +three-dimentsional space. To take full advantage of the arrangement of
```suggestion
three-dimensional space. To take full advantage of the arrangement of
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +                  [1.3 , 0.2, 0.0],
```suggestion
    W = np.array([[0.5,  0.0, 1.5],
                  [1.3,  0.2, 0.0],
```

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +    print(B.n_synapses)
Should we comment that this should be 3 because `tau_syn` has a length of 3? Right now it might not be very clear why we print it. We can also remove it of course, but I think it is useful to know that you can look this up.

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +or by using the ``set()`` function on the SynapseCollection directly:
```suggestion
can then be given as arguments to the ``nest.SetStatus()`` function,
or by using the ``set()`` function on the SynapseCollection directly:
```

Or use a capital O on Or :)

2020-12-18 14:00 UTC, stinebuu commented on doc/guides/connection_management.rst
> +Similar to how you can retrieve several parameters at once with the
```suggestion
Similar to how you retrieve several parameters at once with the
```

2021-01-11 22:21 UTC, jougs reviewed
This review is only for the convenience of being able to suggest changes to myself. No need to look at it really. I fully agree with all your comments and will commit them as a single batch in the next step :smile_cat:

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +arguments are mandatory.
```suggestion
function just takes two NodeCollections containing the source and
target nodes that will be connected in an all-to-all fashion.
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +dictionary, with the mandatory key `synapse_model` as well as optional
```suggestion
dictionary, with optional parameters for the connections.
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +:ref:`Synapse Specification <synapse_spec>`.
```suggestion

The ``syn_spec`` is given as the fourth argument to the ``Connect()``
function. Parameters like the synaptic weight or delay can be either
set values or drawn and combined flexibly from random distributions.
More information about synapse models and their parameters can
be found in the section :ref:`Synapse Specification <synapse_spec>`.
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +or the probability for establishing a connection.
```suggestion
or the probability for establishing a connection. A description of
all connection rules available in NEST is available below.
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
:+1:

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
>  fixed indegree
I think we should leave this as is for now and just wait for the new class-based syntax you are anyway working on in the background and then update this guide again (*sigh*)

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +The `i`th node in ``A`` is connected to the `i`th node in ``B``. The
The following is ugly, but seems to do the trick:
```suggestion
The `i`\ th node in ``A`` is connected to the `i`\ th node in ``B``. The
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +and connections will be using the model `stdp_synapse`. All synapses
```suggestion
and connections will be using synapse model `stdp_synapse`. All synapses
```

2021-01-11 22:21 UTC, jougs commented on doc/guides/connection_management.rst
> +    print(B.n_synapses)
```suggestion
    print(B.n_synapses)   # This will print 3, as we set 3 different tau_syns
```

2021-01-11 22:31 UTC, jougs commented
From my side you you can now merge this to your branch and I'll approve https://github.com/nest/nest-simulator/pull/1834 right after.

Thanks a lot for your thorough review and sorry for the long delay to reply. But I really needed the long Xmas break to shake off 2020. I can't tell you how much I agree with the conclusion from the XKCD below. Naturally, I'm also looking forward to the diving thing ;-)

![](https://imgs.xkcd.com/comics/life_before_the_pandemic.png)

2021-01-12 09:36 UTC, stinebuu approved these changes
Haha! Thanks @jougs!

2021-01-12 09:36 UTC, merged